# Generated by Django 6.0.6 on 2026-08-29 19:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerberos', '0003_alter_agendamento_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='idade',
        ),
        migrations.AddField(
            model_name='pet',
            name='data_de_nascimento',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Data de nascimento do pet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='kerberos.endereco'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido. Ex: (11) 91234-5678 ou 11912345678.', regex='^\\(?\\d{2}\\)?[\\s-]?\\d{4,5}-?\\d{4}$')]),
        ),
    ]
